services:
  - type: web
    name: tabble-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PORT
        generateValue: true
    healthCheckPath: /health